# Apresentação do módulo Numpy


O módulo Numpy é uma extensão em C para Python fundamental para computação científica.
Ele possui uma série de funcionalidades que facilitam o uso de vetores e matrizes. 

Contém entre outras coisas:
* objetos de N-dimensões com funcionalidades poderosas;
* funções sofisticadas e amplas;
* ferramentas para integrar códico C/C++ e Fortran;
* ferramentas de álgebra linear, transformada de Fourier entre outros.


Conforme formos avançando, tente imaginar fazer a mesma coisa usando apenas as funções básicas do Python e listas.

In [1]:
import numpy as np

In [2]:
vetor = np.array([1., 4., 5.3, 2.9])

In [3]:
type(vetor)

numpy.ndarray

Arrays são muito parecidos com listas em vários pontos como por exemplo, particionamento. No entanto, começamos a ver algumas funções embutidas:

In [4]:
print('Valor máximo: ', vetor.max())
print('Valor médio: ', vetor.mean())
print('Desvio padrão: ', vetor.std())
print('Variância: ', vetor.var())

Valor máximo:  5.3
Valor médio:  3.3
Desvio padrão:  1.57638827704
Variância:  2.485


Estamos tratando de um vetor pequeno, mas uma das coisas que precisamos saber é o comprimento do vetor:

In [5]:
vetor.shape

(4,)

Cansou de ser array?

In [6]:
vetor.tolist()

[1.0, 4.0, 5.3, 2.9]

## Matrizes

Até agora parece muito semelhante. Provavelmente você pensou: "eu consigo fazer isso com uma lista". Sim, consegue. Mas vamos complicar um pouco? Que tal trabalharmos com matrizes?

In [7]:
matriz = np.array([[1, 2, 3], [4, 5, 6]], float)
matriz

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

Agora as pequenas funções que vimos, parecem ainda mais interessantes:

In [8]:
matriz.max()

6.0

In [9]:
matriz.shape

(2, 3)

Também temos várias funções para mexer no tamanho da matriz e/ou transpor a matriz

In [10]:
matriz.reshape(3, 2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [11]:
matriz.T

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.]])

In [12]:
matriz.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.])

## Operações entre entre matrizes

Aqui vamos começar a trabalhar com conceitos de eixos. Em python o eixo 0 representa as linhas de uma matriz, enquanto o eixo 1 representa as colunas.

In [13]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

In [14]:
np.concatenate((a,b))

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [15]:
np.concatenate((a,b), axis=1)

array([[ 1.,  2.,  5.,  6.],
       [ 3.,  4.,  7.,  8.]])

## Outros jeitos de criar vetores

In [16]:
np.arange(1., 6., 0.33, dtype=float)

array([ 1.  ,  1.33,  1.66,  1.99,  2.32,  2.65,  2.98,  3.31,  3.64,
        3.97,  4.3 ,  4.63,  4.96,  5.29,  5.62,  5.95])

In [17]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((2,3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Vamos falar sobre matemática
Um dos grandes problemas de trabalhar com listas ao invés de vetores, é executar operações matemáticas em todos os elementos da lista. Em geral, em uma lista, precisamos percorrer todos os elementos para fazer as operações. 

Operações matemáticas com vetores e matrizes são muito mais rápidas e eficientes do que iterações. O Numpy permite que esse tipo de operação aconteça de forma muito simples:

In [20]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a, b

(array([ 1.,  2.,  3.]), array([ 5.,  2.,  6.]))

In [21]:
a + b

array([ 6.,  4.,  9.])

In [22]:
a - b

array([-4.,  0., -3.])

In [23]:
a * b

array([  5.,   4.,  18.])

In [24]:
b / a

array([ 5.,  1.,  2.])

In [25]:
a % b

array([ 1.,  0.,  3.])

In [26]:
b ** a

array([   5.,    4.,  216.])

In [27]:
a > b

array([False, False, False], dtype=bool)

## Valores embutidos
Assim como as funções embutidas Numpy também traz alguns valores famosos embutidos.

In [28]:
np.pi

3.141592653589793

In [29]:
np.e

2.718281828459045

In [30]:
np.nan

nan

In [31]:
np.inf

inf

In [32]:
a = np.array([1, np.nan, 10], float)
np.isnan(a)

array([False,  True, False], dtype=bool)

## Ainda mais mágica do numpy...

In [33]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([ 1.,  4.])

In [34]:
a = np.array([0.5, 3, 1], float)
np.where(a > 1, 1/a, a)

array([ 0.5       ,  0.33333333,  1.        ])